apiVersion: v1
kind: Secret
metadata:
  name: kibana-auth
  namespace: logging
type: Opaque
data:
  # Reference：https://github.com/kubernetes/ingress-nginx/blob/master/docs/examples/auth/basic/README.md
  # The latter part of auth uses base64 encoding
  auth: Y3poZmU6e1NIQX1WS0wxZWJ4VTBuRGZ4UXlacGNaWGV5TVlIRlk9Cg==